---
dist: bionic

language: python
python: "3.7"

addons:
  apt:
    packages:
      - build-essential
      - clang-6.0
      - clang-format-6.0
      - cmake
      - gcc-arm-none-eabi
      - lcov
      - lld-6.0
      - llvm-6.0
      - libboost-dev
      - libnewlib-arm-none-eabi
      - libstdc++-arm-none-eabi-newlib
      - ninja-build

before_install:
  - pip install cpp-coveralls meson

install:
  - |
    : install googletest
    cd $HOME
    curl -L https://github.com/google/googletest/archive/release-1.10.0.tar.gz | tar -xz
    mkdir gtest
    cd gtest
    cmake -G Ninja ../googletest-release-1.10.0
    ninja
    sudo ninja install

script:
  - cd $TRAVIS_BUILD_DIR && mk/update-list.sh
  - meson build.coverage -Db_coverage=true -Dwerror=true
  - meson build.sanitize -Db_sanitize=address,undefined
  - meson build.optimized --buildtype debugoptimized
  - meson build.llvm --native-file mk/native-llvm.txt
  - meson build.thumb --cross-file mk/cross-thumb.txt
  - cd $TRAVIS_BUILD_DIR/build.coverage && ninja test
  - cd $TRAVIS_BUILD_DIR/build.sanitize && ninja test
  - cd $TRAVIS_BUILD_DIR/build.optimized && ninja test
  - cd $TRAVIS_BUILD_DIR/build.llvm && ninja test
  - cd $TRAVIS_BUILD_DIR/build.thumb && ninja

after_success:
  - cd $TRAVIS_BUILD_DIR/build.coverage && ninja coverage
  - lcov --extract meson-logs/coverage.info $(readlink -f ../src)'/*' > $HOME/coverage.lcov
  - coveralls -l $HOME/coverage.lcov -r .. -n
