---
dist: bionic

language: python
python: "3.7"

cache:
  pip: true
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages

addons:
  apt:
    packages:
      - build-essential
      - clang-8
      - clang-format-8
      - lcov
      - lld-8
      - llvm-8
      - libboost-dev
      - ninja-build

before_install:
  - pip install cpp-coveralls cmake meson

install:
  - |
    : install googletest
    cd $HOME
    curl -sL https://github.com/google/googletest/archive/release-1.10.0.tar.gz | tar -xz
    mkdir gtest-build && cd gtest-build
    cmake -G Ninja ../googletest-release-1.10.0
    ninja
    sudo ninja install
  - |
    : install Mbed TLS
    cd $HOME
    curl -sL https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.16.6.tar.gz | tar -xz
    mkdir mbedtls-build && cd mbedtls-build
    cmake -G Ninja ../mbedtls-mbedtls-2.16.6 -DENABLE_PROGRAMS=0 -DENABLE_TESTING=0
    ninja
    sudo ninja install
  - |
    : install Arduino
    sudo iptables -A INPUT -p udp -m udp --dport 5353 -j DROP
    export INSTALL_PLATFORMS='esp8266,esp32,nrf52'
    source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh | \
             sed -e '/sudo pip3/ d' -e 's/pip3 install --user/pip install/')

script:
  - cd $TRAVIS_BUILD_DIR && mk/update-list.sh
  - meson build.coverage -Db_coverage=true -Dwerror=true -Dunittest=enabled
  - ninja -C build.coverage test
  - |
    travis_fold start "build.coverage/testlog"
    cat build.coverage/meson-logs/testlog.txt
    travis_fold end "build.coverage/testlog"
  - meson build.sanitize -Db_sanitize=address,undefined -Dunittest=enabled
  - ninja -C build.sanitize test
  - |
    travis_fold start "build.sanitize/testlog"
    cat build.sanitize/meson-logs/testlog.txt
    travis_fold end "build.sanitize/testlog"
  - LDFLAGS='-fuse-ld=lld -L/usr/local/lib' meson build.llvm --native-file mk/native-llvm.txt --buildtype debugoptimized -Dunittest=enabled
  - ninja -C build.llvm test
  - |
    travis_fold start "build.llvm/testlog"
    cat build.llvm/meson-logs/testlog.txt
    travis_fold end "build.llvm/testlog"
  - build_platform esp8266
  - build_platform esp32
  - build_platform nrf52840

after_success:
  - cd $TRAVIS_BUILD_DIR/build.coverage && ninja coverage
  - lcov --extract meson-logs/coverage.info $(readlink -f ../src)'/*' > $HOME/coverage.lcov
  - coveralls -l $HOME/coverage.lcov -r .. -n
