---
dist: bionic

language: python
python: "3.7"

addons:
  apt:
    packages:
      - build-essential
      - clang-format-6.0
      - cmake
      - lcov
      - libboost-dev
      - ninja-build

before_install:
  - pip install cpp-coveralls meson

install:
  - |
    : install googletest
    cd $HOME
    curl -L https://github.com/google/googletest/archive/release-1.10.0.tar.gz | tar -xz
    mkdir gtest
    cd gtest
    cmake -G Ninja ../googletest-release-1.10.0
    ninja
    sudo ninja install

script:
  - cd $TRAVIS_BUILD_DIR && mk/update-list.sh
  - meson build.coverage -Db_coverage=true
  - meson build.sanitize -Db_sanitize=address,undefined
  - cd $TRAVIS_BUILD_DIR/build.coverage && ninja test
  - cd $TRAVIS_BUILD_DIR/build.sanitize && ninja test

after_success:
  - cd $TRAVIS_BUILD_DIR/build.coverage && ninja coverage
  - lcov --extract meson-logs/coverage.info $(readlink -f ../src)'/*' > $HOME/coverage.lcov
  - coveralls -l $HOME/coverage.lcov -r .. -n
